export const types = {
  // Products
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  FETCH_PRODUCT: "FETCH_PRODUCT",
  CREATE_PRODUCT: "CREATE_PRODUCT",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",


  // Auth
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",

  // loading
  START_LOADING: "START_LOADING",
  STOP_LOADING: "STOP_LOADING",
}